# Generated by Django 6.0.7 on 2026-07-31 11:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadlineevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadlineevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='deadlineevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='schedule.deadline'),
        ),
        migrations.AddField(
            model_name='deadlineevent',
            name='status',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.deadlinescheduleitemstatus'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deadlines', to='schedule.deadlinescheduleitemstatus'),
        ),
        migrations.AddField(
            model_name='deadlineevent',
            name='type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.deadlinescheduleitemtype'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='schedule.deadlinescheduleitemtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='schedule.event'),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='status',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.eventscheduleitemstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_events', to='schedule.eventscheduleitemstatus'),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='schedule.eventscheduleitemtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='schedule.eventscheduleitemtype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='deadline',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "schedule_deadlineevent" ("created_at", "created_by_id", "deactivated_at", "description", "due_time", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "title", "type_id", "updated_at") VALUES (NEW."created_at", NEW."created_by_id", NEW."deactivated_at", NEW."description", NEW."due_time", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status_id", NEW."title", NEW."type_id", NEW."updated_at"); RETURN NULL;', hash='919a78b1a5eb12ba12da557be61931c84d3137be', operation='INSERT', pgid='pgtrigger_insert_insert_8edca', table='schedule_deadline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='deadline',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "schedule_deadlineevent" ("created_at", "created_by_id", "deactivated_at", "description", "due_time", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "title", "type_id", "updated_at") VALUES (NEW."created_at", NEW."created_by_id", NEW."deactivated_at", NEW."description", NEW."due_time", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status_id", NEW."title", NEW."type_id", NEW."updated_at"); RETURN NULL;', hash='1bb73d1116dc4250f4f07939ec91c183fb73c15b', operation='UPDATE', pgid='pgtrigger_update_update_e1c03', table='schedule_deadline', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='event',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "schedule_eventevent" ("created_at", "created_by_id", "deactivated_at", "description", "end_time", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time", "status_id", "title", "type_id", "updated_at") VALUES (NEW."created_at", NEW."created_by_id", NEW."deactivated_at", NEW."description", NEW."end_time", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_time", NEW."status_id", NEW."title", NEW."type_id", NEW."updated_at"); RETURN NULL;', hash='b6730b6dbd2e736756b6b49cee6ac831d89e55cd', operation='INSERT', pgid='pgtrigger_insert_insert_e6f58', table='schedule_event', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='event',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "schedule_eventevent" ("created_at", "created_by_id", "deactivated_at", "description", "end_time", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time", "status_id", "title", "type_id", "updated_at") VALUES (NEW."created_at", NEW."created_by_id", NEW."deactivated_at", NEW."description", NEW."end_time", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_time", NEW."status_id", NEW."title", NEW."type_id", NEW."updated_at"); RETURN NULL;', hash='f9c9493d1272c6503c8c3c21a7ade13f6ccf1303', operation='UPDATE', pgid='pgtrigger_update_update_0c68f', table='schedule_event', when='AFTER')),
        ),
    ]
